name: hf
# PyTorch: CUDA 12.1
# Tensorflow: CUDA 11.8
channels:
  - pytorch
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.10.*
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.*
  #- cudatoolkit=11.8.0
  #- cudnn=8.8.0.121
  #- tensorflow=2.10.0
  - pytorch::pytorch=2.1.2
  - pytorch::torchaudio=2.1.2
  - pytorch::torchvision=0.16.2
  # - pip:
  #   - tensorflow==2.10.1 # GPU-enabled!

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
  - win-64
